### ISSUE TITLE
Server Crash - Ticking Entity

### ISSUE THREAD

**Issue by kezmodius** [tasgon/observable#100]
https://gist.github.com/kezmodius/94775f5b3f88d5e2819bb7dfa9e47edf

A player on my server approached a Piglin Brute. Server crashed. He rejoined and tried to run from it. Crashed again (see attached log). Next time he rejoined he got far enough away to stop the crashes.

Crash log pointed to Observable and Canary. I will report the issue there too.

I would appreciate knowing what, if anything, I can do to avoid further crashes. Thank you.

**Comment by kezmodius** [comment]
https://gist.github.com/kezmodius/e83d1fa2f69f152b9be112831c40c26c
My server crashed twice again today with the same issue. This time the player was in the Blood Magic dimension, instead of the Nether, but it was still a Piglin Brute that crashed. I can't read logs (apart from the obvious) so I would really appreciate if you can tell me what's crashing so I can stop the player using it (if he is at fault).

I have also reported this issue here: https://github.com/AbdElAziz333/Canary/issues/238

**Comment by tasgon** [comment]
Due to the observable's nature, Forge will always suspect it as a cause of the crash, but in this case it seems unlikely.
