### ISSUE TITLE
Multiple Players cannot use the profiler.

### ISSUE THREAD

**Issue by fabrossmann** [tasgon/observable#15]
Playing on ATM 6 1.8.8
If one player uses the profiler, no one else can. The only way to use it, is to reconnect.
![image](https://user-images.githubusercontent.com/6189957/139525359-0c1e6e73-0f02-4ba5-85bd-effb97846458.png)

**Comment by tasgon** [comment]
I'm fairly certain I know what's causing this, so I should have a fix out shortly.

**Comment by tasgon** [comment]
[This version should have the fix.](https://github.com/tasgon/observable/files/7491397/observable-0.1.4-forge.zip) Still working on getting a new version out on CurseForge, but in the meantime, let me know if you spot any bugs in it.

**Comment by tasgon** [comment]
[0.2.0](https://github.com/tasgon/observable/releases/tag/0.2.0) has now been uploaded to here and CurseForge with the fix.
