### ISSUE TITLE
Unable to use mod in Fabric 1.17 dev environment

### ISSUE THREAD

**Issue by Domaman202** [tasgon/observable#17]
![image](https://user-images.githubusercontent.com/51743763/140595464-afba4b01-28f5-479a-9a3f-ce5d2ab6d3a9.png)
IDK HOW FIX THIS XD

**Comment by tasgon** [comment]
Huh, this is a bug. Might take me a while to investigate, currently fixing some stuff up for 1.16, sorry.

**Comment by Domaman202** [comment]
ok

**Comment by Domaman202** [comment]
F

**Comment by tasgon** [comment]
Should be fixed in the 1.18 branch.
