### ISSUE TITLE
Feature request partial functionality for Non-OP users

### ISSUE THREAD

**Issue by BrettMoan** [tasgon/observable#21]
Feature request, non-op viewing of profiles ran by other players. 

After reading and looking in code its clear that a user needs OP to run the tool to generate the data for the overlay.

However it would would be nice if viewing the overlay didn't require OP, like if users could just see the overlay of ran profiles, (but not actually execute them nor be able to TP). 

I assume this would require a difference in how you save and persisted data, and would still require an OP to run the profile either through the mod interface or commands.

**Comment by tasgon** [comment]
I'll probably make it so that you can give people permissions to run the profiler, however making it accessible to everyone also gives them essentially x-ray in a lot of ways (even just looking at previously run profiles) so I have to make sure to balance it correctly.

**Comment by BrettMoan** [comment]
maybe you can make it a custom permission as well?

I play on servers with "role" plugins for example that give you permissions over time, and then owner gives roles to in game mods and things, so being able to have/not-have permissions to the overlay would make sense to.

but yeah, the overlay for sure gives x-ray, which when you are /op is actually really important, but for non-op i could see why that would be un-desired. Idk much about how the game rendering works, but depending on difficulty the rendering code could also maybe not-be xray for non-op?

might not be an option , but it if it is, its another possible route to go.

**Comment by tasgon** [comment]
The x-ray isn't the main thing I'm worried about. It is one factor, the the principal problem is the fact that the current system sends information about *all* entities (including players) in the world, even ones that are not loaded into the client, so it would make it nearly impossible to hide bases on e.g. anarchy servers.

There are a few solutions I can think of for that, however implementing it needs to be done with care. I'll am prioritizing a permissions system, but I'm still debating whether I want to depend on an external library for this or set up something basic myself.

**Comment by WeasleyWalls** [comment]
Would love to see some way to make the ui available to normal players. After very briefly looking into this I see that FTB's permission system relies on command nodes(args?) to allow the user given access to run very specific part of that command. 

Hell, even just a simple config with a bool if you want to allow all players to see results would be enough for me.

Now, I don't have any experience in coding for minecraft mod and just throwing out a idea. Maybe adding commands to trigger different parts of the ui would work?

And example of that is if you wanted a profiler to run for 30 sec you would type '/observable profiler 30'. This could then have the command nodes: 
command.observable
command.observable.profiler
command.observable.profiler.time

Or if you just wanted to open the result screen you would type '/observable result' which would have the command nodes:
command.observable
command.observable.result

**Comment by bdspark** [comment]
is non op users feature updated?. really want to use this for my server. can anyone confirm please?

**Comment by tasgon** [comment]
I'm going to try to get around to this at some point soon(ish), but I've got a few other things I'm working on and can't afford to prioritize it as much as I'd like. Hopefully, I should have some free time over the next two weeks to pull this off, but no promises.

**Comment by veber01** [comment]
any update on this topic?

**Comment by Normal69** [comment]
Anarchy servers don't need this.
Maybe an option in the config, the radius of the scan for a non-admin?
It was like this in the other mod of 1.12.2

**Comment by tasgon** [comment]
Added in 3.3.0 for 1.19, backporting to 1.18 in progress (1.16 TBD).

**Comment by TheInfamousAlk** [comment]
Is there any documenation on this and how to use the permissions?
