### ISSUE TITLE
Latest version breaks the DoubleSlabs mod

### ISSUE THREAD

**Issue by starmun-0010** [tasgon/observable#23]
**Description**
Placing a slab down from double slabs, in the presence of observable mod causes a crash. The  issue does not happen with the previous version of the mod.

**Versions**
- Minecraft: 1.16.5
- Forge: 36.2.22
- Observable: 0.2.0
- Double Slabs: 3.7.2

**Steps to  Reproduce**
1. Install Observable & dependencies
2. Install [double slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs) mod
3. Start a world
4. spawn or make a vertical slab from double slabs
5. Place it down
6. Crash

**Logs**
[Latest Log](https://gist.github.com/starmun-0010/af75aacd4d9f7360495dad1446dfdd9e)
[Crash Log](https://gist.github.com/starmun-0010/18dbae033461f12e2ff5accb7a613abf)

**Comment by tasgon** [comment]
This is on my end. I'll have a fix out by the end of the day.

**Comment by tasgon** [comment]
Try [this version](https://github.com/tasgon/observable/releases/tag/0.2.1) and let me know if it fixes the problem.

**Comment by starmun-0010** [comment]
yes, 0.2.1 fixes the double slabs issue.

**Comment by tasgon** [comment]
Alright, I'll post the new version as soon as CurseForge comes back up.
