### ISSUE TITLE
Modrinth release outdated ?

### ISSUE THREAD

**Issue by yesn0t** [tasgon/observable#25]
Hi, if possible could you please upload the recent versions to your modrinth ? thanks x)

**Comment by tasgon** [comment]
Yeah, sorry, I'll try to get an update out on there soon(ish), however I do keep the mod updated on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/observable). Would that work for now?

**Comment by yesn0t** [comment]
no worries !  would usually prefer modrinth for its lightweight frontend but github releases also do the trick :+1:

**Comment by tasgon** [comment]
I've updated the mod on Modrinth for both 1.16 and 1.18, so I'll close the issue for now. Note that I two files for each version, one for Forge and one for Fabric. If this poses a problem, reopen the issue and let me know.

**Comment by yesn0t** [comment]
thanks !
