### ISSUE TITLE
Unable to change font scale

### ISSUE THREAD

**Issue by skerit** [tasgon/observable#28]
When dragging the font scale slider, I get this error:

![afbeelding](https://user-images.githubusercontent.com/755212/165519068-c3fda583-c3ba-4552-80f9-fe91cbb7b90e.png)

I'm guessing it's a locale thing, where the program espects a point to be used as the decimal spacer but a comma is used instead?

**Comment by tasgon** [comment]
Have you tried setting it to 3.5 manually by double clicking on the box and typing?

**Comment by tasgon** [comment]
Observable as of *.3.0+ versions no longer uses an in-game results screen. These changes are out for 1.19, and I'm currently working on backporting the changes to 1.18.
