### ISSUE TITLE
v2.3.3 Fails to load on Forge 1.18.2-40.1.0

### ISSUE THREAD

**Issue by isaaclepes** [tasgon/observable#29]
![image](https://user-images.githubusercontent.com/54421422/165665902-0e599263-a116-44fc-bda3-5304dbda6efd.png)
[latest.log](https://github.com/tasgon/observable/files/8579107/latest.log)
[debug.log](https://github.com/tasgon/observable/files/8579108/debug.log)

**Comment by tasgon** [comment]
You need the Kotlin standard library, which a mod such as [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge) can provide.
