### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by LatvianModder** [tasgon/observable#3]
I really love this mod. but I would like if there was way to merge/hide all the block entities that use 0 micro s/t in the individual list (and in-world) since that seems to be the vast majority of results:

![](https://cdn.discordapp.com/attachments/794742192392110110/871135029923811358/unknown.png)
![](https://cdn.discordapp.com/attachments/794742192392110110/871134601807032351/unknown.png)

**Comment by tasgon** [comment]
![2021-07-31_18 28 00](https://user-images.githubusercontent.com/10052313/127753817-c4d06d88-4f2e-452b-aa3c-94819b835afd.png)

Something like this look good to you?

**Comment by LatvianModder** [comment]
Yeah I think thats good!

**Comment by tasgon** [comment]
Alright then, closing this issue for now.
