### ISSUE TITLE
Profiler not working

### ISSUE THREAD

**Issue by Sebas-Re** [tasgon/observable#30]
Every time the profiler tries to send the results, I get this error:

https://paste.corebot.dev/xemuvatapu.php

**Comment by tasgon** [comment]
This seems to be an error internal to the serialization library I'm using. Could you provide the full log file?

**Comment by Sebas-Re** [comment]
Sure, client or server?

**Comment by tasgon** [comment]
The more, the merrier.

**Comment by tasgon** [comment]
Closing due to no response in 5 months
