### ISSUE TITLE
Crash on launch DW20 V1.2.0

### ISSUE THREAD

**Issue by blacksythe** [tasgon/observable#31]
[crash-2022-05-20_12.31.28-fml.txt](https://github.com/tasgon/observable/files/8742443/crash-2022-05-20_12.31.28-fml.txt)

Crash on server start with observable and architectury build 60 MC 1.18.2

Java openjdk17

**Comment by tasgon** [comment]
Just to make sure, do you have both Architectury and Kotlin for Forge installed? I only see one of those mods in the mod list. After that, if it still continues crashing, let me know what custom mods you're using so I can try to replicate it on my end.

**Comment by tasgon** [comment]
Closing due to no response in 5 months
