### ISSUE TITLE
Won't start with Observable

### ISSUE THREAD

**Issue by qwewer0** [tasgon/observable#32]
I get the following crash report when trying to open the game:
[crash-2022-06-06_14.01.34-client.txt](https://github.com/tasgon/observable/files/8844261/crash-2022-06-06_14.01.34-client.txt)

Tested it with the following:

- Java 18.0.1.1
- Fabric loader 0.14.6
- Architectury API 4.4.68 (fabric)
- Fabric api 0.55.1 (1.18.2)
- Observable 2.2.3 (fabric)

**Comment by tasgon** [comment]
You're missing [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
