### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by Avakining** [tasgon/observable#33]
If possible, could observable be updated to 1.19? Thank you!

**Comment by tasgon** [comment]
I'm about halfway through with it. I'll try to get a release out ~~this weekend~~ as soon as I figure out how to make `kotlin-imgui` work with the new version of LWJGL in 1.19. Sorry about the wait.

**Comment by tasgon** [comment]
I have some early 1.19 releases being built in CI [here](https://github.com/tasgon/observable/actions/). I'll close this issue as soon as I have a more stable release out on CF/Modrinth
