### ISSUE TITLE
[Enhancement] [Feature] server console methods - generate profile - export reports

### ISSUE THREAD

**Issue by mjevans** [tasgon/observable#34]
It would be nice to also be able to use this mod from the server console.  The workflow would be a tiny bit different but it'd mostly be the same outputs already in the data lists on screen.

server console methods:

- observable profile (duration, other args)
- observable save-report (type(s)) (filename/basename)

An additional report that batches chunk time reports by groups of load tickets would also be spectacular.

**Comment by tasgon** [comment]
Console commands added in 3.3.0
