### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by Nevrai** [tasgon/observable#35]
The game crashes on start-up with Observable installed.

**Crash report:** https://pastebin.com/raw/ZwmURCqB

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest for 1.18.2)
* **Observable:** 2.2.3 (Forge)

**Comment by tasgon** [comment]
Do you have [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge) installed?

**Comment by Nevrai** [comment]
Didn’t realize that was a dependency. I had to disable it [because of a crash](https://github.com/thedarkcolour/KotlinForForge/issues/47). That explains it, then.
