### ISSUE TITLE
OpenGL Error (GL_INVALID_OPERATION) at mainLoop

### ISSUE THREAD

**Issue by mouro001** [tasgon/observable#37]
I get this message in chat:
> Error performing action: OpenGL Error (GL_INVALID_OPERATION) at mainLoop
> Please report this at github.com/tasgon/observable/issues

Whenever trying to see the results after using the Shrink mod to make myself smaller
I had the Shrink set to 0.2 and tried to open the results.

After changing the value that Shrink has it started working again.

Modpack: All The Mods 7.

**Comment by tasgon** [comment]
Sounds like a duplicate of #12
