### ISSUE TITLE
[Forge] GUI key rebind

### ISSUE THREAD

**Issue by BEMZ01** [tasgon/observable#38]
Is there any way to rebind / disable the GUI? I've looked through the config folder and can't see observable there.

**Comment by tasgon** [comment]
Try searching 'profiler' in the keybinds list.

**Comment by KajesLorian** [comment]
I figured it out BEM. You need to install Observable on your client as well to get the option to use the GUI in any way, shape, or form. Before doing so I was having the same issue.
