### ISSUE TITLE
Observable scan finds entities around spawn

### ISSUE THREAD

**Issue by morceaudebois** [tasgon/observable#39]
Hi! I just found out about this plugin, it's really cool and well made :)

As you could guess, I'm trying to find out why my servers lags so much in certain areas. I did a 30 seconds scan and managed to find a few issues I could fix, but I noticed something weird: some of the entities that appear in the scan are actually at spawn, which is 2000 blocks away from the area I'm scanning. I'm not sure if that's actually a problem with my server or only an Observable bug. I thought it might be related to waystones but I'm not sure either. 

Any idea what's going on here? Here's the full report: https://o.tas.sh/#1eZY

Thank you!

**Comment by tasgon** [comment]
This is likely because [spawn chunks are always loaded](https://minecraft.fandom.com/wiki/Spawn_chunk), at least so long as you're in the same dimension. If you go to the nether, do you still see this happening?

**Comment by tasgon** [comment]
Doesn't seem to be an actual problem, so I'm closing this.
