### ISSUE TITLE
'Visit' Command for Chunks Incorrect 

### ISSUE THREAD

**Issue by Avakining** [tasgon/observable#42]
The 'Visit' command linked in the 'Chunks' section of the website teleports the user to the coordinates listed, instead of the *chunk* coordinates.

Example command: `/observable tp minecraft:overworld position -62 128 4` -- which is pasted from the 'Chunks' section -- should teleport to the *chunk* -62, 4 but instead teleports to the *block* -62, 128, 4

**Comment by tasgon** [comment]
Web UI code should be fixed now to give the right command. Let me know if you're still seeing the issue.
