### ISSUE TITLE
[1.19.3] Client crash with only this mod - Caused by 0: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProsperCraft** [tasgon/observable#44]
https://gist.github.com/ProsperCraft/eadec1eb517bec6c3240b2084d70f5b6

**Comment by tasgon** [comment]
You are missing a dependency mod, Kotlin for Forge. Add that and it should work.

**Comment by ProsperCraft** [comment]
Please add that as a dependency of the mod so it gets installed when Observable does.

Thank you for the help, it loads now.
