### ISSUE TITLE
Allow disabling log uploads

### ISSUE THREAD

**Issue by ParzivalWolfram** [tasgon/observable#47]
I would prefer the option to disable the default behavior of uploading the log to a third-party server, and just view the results in my client. I'm debugging poor performance issues in a large modpack, so I may wind up making 30-40 reports in a row doing various things to check what's performing so poorly. This would likely cause issues with this behavior, so I would like the ability to operate entirely locally.

**Comment by tasgon** [comment]
I made it so that profiles are now saved locally if they fail to upload (which you can open client-side in the web UI), so that should hopefully make your problem a bit less bad.

**Comment by SomeGuyOnTheInternet2** [comment]
LATE COMMENT "profiles are now saved locally if they **fail to upload**"
why cant uploading be disabled, also why did it move from in game gui to forced upload or it being required to use a website(not that the json is unusable but), what's the config for it's literally just empty {}

**Comment by ParzivalWolfram** [comment]
> LATE COMMENT "profiles are now saved locally if they **fail to upload**" why cant uploading be disabled, also why did it move from in game gui to forced upload or it being required to use a website(not that the json is unusable but), what's the config for it's literally just empty {}

I have much the same sentiment, but I just moved on to using JVisualVM, since it doesn't force me to upload logs to someone else and gives me the ability to record JVM state over time. It's not worth arguing with a mod author over not having to upload data to a custom viewer website to use a mod properly.

**Comment by uninstall-your-browser** [comment]
LATER COMMENT for future reference
you are able to disable uploads by running
```
/observable set uploadURL "http://dont.fucking.upload.invalid"
```
Or whatever you feel like, as long as it's not a real website.
