### ISSUE TITLE
Observable crashing on server

### ISSUE THREAD

**Issue by KeksNino** [tasgon/observable#48]
[latest.log](https://github.com/tasgon/observable/files/11008507/latest.log)
crashing on startup

Modlist:
[modlist.txt](https://github.com/tasgon/observable/files/11008520/modlist.txt)

**Comment by tasgon** [comment]
Adding [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge) should fix the issue.

**Comment by KeksNino** [comment]
i already have kotlin for forge in the modpack
