### ISSUE TITLE
[Forge] "ArrayIndexOutOfBoundsException: -1" Crash while trying to make a window wider

### ISSUE THREAD

**Issue by aaronhowser1** [tasgon/observable#5]
https://pastebin.com/6CGFyLhp

**Comment by tasgon** [comment]
This is likely an Imgui issue. I'll try to diagnose the issue and file a report on their repo. In the meantime I'll probably just surround all Imgui rendering in a try catch clause since none of the errors there should be able to affect the rest of the game

**Comment by tasgon** [comment]
Fixed in master
