### ISSUE TITLE
Crash on modpack at startup 1.19.2

### ISSUE THREAD

**Issue by BlackAures1** [tasgon/observable#54]
[crash-2023-05-19_22.17.53-fml.txt](https://github.com/tasgon/observable/files/11519841/crash-2023-05-19_22.17.53-fml.txt)
All info inside

**Comment by tasgon** [comment]
Install Kotlin for Forge (see mod description on CurseForge).

**Comment by BlackAures1** [comment]
Don't you have Relation for automatic loading in Curseforge? In previous versions, it was downloaded automatically.

**Comment by tasgon** [comment]
Turns out I hadn't actually added it as a dependency. Sorry about that, it's fixed now.
