### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by tasgon** [tasgon/observable#58]

**Comment by windy664** [comment]
![Screenshot_2023-08-01-20-34-58-234_com microsoft rdc android](https://github.com/tasgon/observable/assets/81475218/892767c9-79d1-4f50-a397-e6bebd63d04e)
me too
help me , my tps was too low!

**Comment by douglasg14b** [comment]
Yes, please! 1.20.1 support would be wonderful. What sort of effort would this take? Do you need help, or?

**Comment by tasgon** [comment]
Done.
