### ISSUE TITLE
[Forge] Cannot close windows with their X buttons

### ISSUE THREAD

**Issue by aaronhowser1** [tasgon/observable#6]
![image](https://user-images.githubusercontent.com/15698722/128130879-e8f1bb0b-09ff-4c5c-9afa-b4377abdccd7.png)
Clicking this does nothing

**Comment by tasgon** [comment]
That is intentional, as I wouldn't want people to accidentally close a window and the imgui library I'm using doesn't let me hide the button (as far as I can see). I'll look more into it.

**Comment by tasgon** [comment]
Fixed in master.
