### ISSUE TITLE
Error when clicking "Get URL" button

### ISSUE THREAD

**Issue by dhasial** [tasgon/observable#61]
The message is simply `Error: no protocol:`

I looked in the config file to see if there was a way to set a protocol, but it was only empty brackets. Also, this is a singleplayer and modded (fabric launcher) instance.

**Comment by tasgon** [comment]
Honestly, if you're talking about the "Get!" button in the profiler screen, I just removed that feature because I think it's fairly confusing and I don't think anyone used it.
