### ISSUE TITLE
Error when rendering the results for the TPS profiler

### ISSUE THREAD

**Issue by PigNuggets** [tasgon/observable#62]
When I tried to use the tps profiler, all the blocks were just green or other colors, no numbers showed up like they should.

![2023-08-04_16 47 54](https://github.com/tasgon/observable/assets/73538208/57740ebc-e362-4479-a062-3d45a7f5ce81)

**Comment by tasgon** [comment]
What Minecraft version, Java version, and Observable version are you running? This may be related to https://github.com/tasgon/observable/issues/59.

**Comment by tasgon** [comment]
No response in ~6 months, closing
