### ISSUE TITLE
Upload fails because server returns response code 500

### ISSUE THREAD

**Issue by andriihorpenko** [tasgon/observable#63]
Upload fails due to HTTP response code 500.
I should also note that is worked fine yesterday.
<img width="1014" alt="image" src="https://github.com/tasgon/observable/assets/13716167/2e263d69-01dc-4688-9d82-e4c65c91ed9f">

**Comment by O2theC** [comment]
i am having the same problem on fabric 1.19.2 but for me it didn't work at all, had just installed the mod

**Comment by tasgon** [comment]
Sorry about that, should be fixed now. Let me know if it's still broken

**Comment by O2theC** [comment]
seems to work for me now, thx for the fix

**Comment by andriihorpenko** [comment]
Likewise, thanks!
