### ISSUE TITLE
observable-3.3.1       Mod loading error has occurred   Crash on Startup Forge 1.19.2

### ISSUE THREAD

**Issue by Minebrah** [tasgon/observable#66]
Crash log:

https://gist.github.com/Minebrah/b790b2b1012a6f0240fec06634cddbeb

Debug log:

https://gist.github.com/Minebrah/7d78365467ac1e8c0fe3daaf0ef2a76b

**Comment by tasgon** [comment]
See #57. Install [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge) to fix this.
