### ISSUE TITLE
[1.20.1] Unable to see data sheets.

### ISSUE THREAD

**Issue by Reshy** [tasgon/observable#69]
When activating the profiler, you are unable to open the "https://o.tas.sh/" or the older stand along profiler screen greatly limiting it's ability.

![image](https://github.com/tasgon/observable/assets/2096384/328ea59d-e9b0-4596-842b-a8b2cdfee97c)

**Comment by Normal69** [comment]
On 1.20.1the same thing for me.

**Comment by Somnioblivio** [comment]
Have this same issue, 1.20.

manually added it to DW20s 1.20 pack on FTB, server is hosting and has the mod installed on server and locally.

**Comment by tasgon** [comment]
Sorry, just now getting a chance to review these issues. What exactly do you mean? Is the website not working for you? What kind of error is it giving you?

**Comment by jennLumm** [comment]
> Sorry, just now getting a chance to review these issues. What exactly do you mean? Is the website not working for you? What kind of error is it giving you?

in game :
![2024-02-22_11 02 16](https://github.com/tasgon/observable/assets/137164497/3ee8725a-5af9-48b9-98d0-90a0d2cac1c0)

website :
![2024-02-22 110037](https://github.com/tasgon/observable/assets/137164497/62f3d7d1-ec40-4174-9155-ee438f912793)

it's been working well so far and today i got this error
im in 1.20.1 / observable-4.4.1

**Comment by tasgon** [comment]
This issue should be resolved now, so I'm closing this issue. Please reopen it if you're still encountering it.

**Comment by jennLumm** [comment]
> This issue should be resolved now, so I'm closing this issue. Please reopen it if you're still encountering it.

ow sorry for wrong post
