### ISSUE TITLE
[Forge] Visit button does not work

### ISSUE THREAD

**Issue by aaronhowser1** [tasgon/observable#7]
![image](https://user-images.githubusercontent.com/15698722/128130942-a16a3993-0f44-4af3-bf78-f40c52b8496d.png)
Clicking this does nothing.

Actually while typing this it crashed. Here is the crash report: https://pastebin.com/5dN8CWWN

**Comment by tasgon** [comment]
The visit button won't work on entities that die afterwards. I can try to add in info on the last known position if that's desirable. As for the crash, I'll looo into it.

**Comment by aaronhowser1** [comment]
I tried on several, none of them had died in the mean time.

**Comment by tasgon** [comment]
Huh. Can you send me the world file, and is this on Academy?

**Comment by aaronhowser1** [comment]
This is in University 1.16, which currently isn't public.

Just tested it again and it totally worked. I am very confused now.
