### ISSUE TITLE
1.20.1 Forge Server Crash

### ISSUE THREAD

**Issue by Yokaaaaaaa** [tasgon/observable#72]
Hello I was just playing with my friends and everytime I hit mobs the server crashes and every once again the server shuts down when I try to rejoin. Can someone help us with it pls :)
[crash-2023-12-16_18.01.59-server.txt](https://github.com/tasgon/observable/files/13693321/crash-2023-12-16_18.01.59-server.txt)

**Comment by Jamdog** [comment]
Could we get some resolution notes on this from the OP...?
It has been closed by the person who logged the issue, but doesn't say what was done to fix it.
Now I am having exactly the same problem, and have no idea how to fix it.
**My Crash Details**
Modpack: All the Mods 9
Modpack Version: 0.2.31
Forge Version: 47.2.16
Minecraft Version: 1.20.1
It seems to affect minecraft vanilla bees being ticked when on Abydos (Stargate Journeys mod).
Crash occurs whenever the chunk containing these bees is loaded
[crash-2023-12-21_22.45.40-server.txt](https://github.com/tasgon/observable/files/13752015/crash-2023-12-21_22.45.40-server.txt)

**Comment by Yokaaaaaaa** [comment]
Hello, I am sorry,

I just had the Invisibility Cloak from Reliquary activated and in my inventory. I simply put the Item away, and then everything went fine. It was a common bug, my friend helped me. Sorry for not clarifying it. Hope it works for u as well! <3

**Comment by Jamdog** [comment]
Thanks!  Not my issue though, oddly...
The crash happens when any player gets close to the affected area, close enough to load the chunk.  No-one is wearing an Invisibility Cloak at the time.
