### ISSUE TITLE
Key 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [tasgon/observable#79]
observable-4.4.1.jar

> [00:55:33] [Worker-ResourceReload-3/WARN] [de.ar.re.cl.ke.fo.KeyMappingRegistryImpl/]: Key mapping key.observable.profile registered after event
> java.lang.RuntimeException: null
> 	at dev.architectury.registry.client.keymappings.forge.KeyMappingRegistryImpl.register(KeyMappingRegistryImpl.java:47) ~[architectury-9.2.14-forge.jar%23450!/:?] {re:classloading}
> 	at dev.architectury.registry.client.keymappings.KeyMappingRegistry.register(KeyMappingRegistry.java) ~[architectury-9.2.14-forge.jar%23450!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at observable.Observable.clientInit(Observable.java:151) ~[observable-4.4.1.jar%23633!/:?] {re:mixin,re:classloading}
> 	at observable.forge.ObservableForge.onClientInit(ObservableForge.java:28) ~[observable-4.4.1.jar%23633!/:?] {re:classloading}
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23109!/:?] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.7.jar%23728!/:?] {}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.7.jar%23727!/:?] {re:mixin}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

**Comment by PoptartKing99** [comment]
I have the same error with just observable installed.
