### ISSUE TITLE
Allow changing the upload server 

### ISSUE THREAD

**Issue by MojangPlsFix** [tasgon/observable#82]
It would be nice to change the upload server to a self-hosted one like in [spark](https://spark.lucko.me/docs/Configuration#viewerurl).
This benefits bigger servers that must be GDPR-compliant and minimize internal server data shared with third-party services.

**Comment by tasgon** [comment]
I'll take a look at this at some point, but if you block requests from your minecraft server to my upload server, it should write the profiling data to your local machine. You then should be able to open the file at https://o.tas.sh, which will show you the results _without_ uploading the file to the server.

Not an ideal experience, but if you're having problems with GDPR, this might work as a stopgap.

**Comment by tasgon** [comment]
Resolved in 756e4dc459899b2a028c86da8c60dafe0721eeed
