### ISSUE TITLE
AE2 stuff not showing up

### ISSUE THREAD

**Issue by RedAngel121** [tasgon/observable#86]
Applied Energistics 2 items are not showing up when using the observable microsecond overlay
![image](https://github.com/tasgon/observable/assets/33588872/6e8b2d9a-4925-471a-b18f-4a1c34da8c64)
![image](https://github.com/tasgon/observable/assets/33588872/9266feb4-f44e-421b-b275-faf77f49115c)

**Comment by tasgon** [comment]
From what I understand, AE2 uses a separate ticking system which prevents it from showing up in the overlay.
