### ISSUE TITLE
ATM9 - To the sky (Productive bees)

### ISSUE THREAD

**Issue by Wolfmann13** [tasgon/observable#89]
Hi, i was trying to spawn inn productive bees gene bottle but i think i fk a lil bit up and cant go into the server because it crashes the game. 

I get a error like this: 
![Screenshot 2024-06-13 204628](https://github.com/tasgon/observable/assets/172638979/3dc38167-a4db-440d-b5ff-3c085ece6f21)

Does anyone know how to fix it?

**Comment by tomtenberge** [comment]
nothing in this crash report says anything about observable, try asking on the support page for productive bees?

**Comment by tasgon** [comment]
Yeah, this is probably not actually related to my mod, closing. Feel free to reopen the issue if you can demonstrate Observable is causing it.
